# frozen_string_literal: true

source "https://rubygems.org"

gemspec

# Use the core gem from this repo while developing the two together.
gem "api_steward", path: ".."

group :development, :test do
  gem "minitest", "~> 5.0"
  gem "rake", "~> 13.0"
end
